# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guillobits/workspace/epitech/PSU_2016_zappy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guillobits/workspace/epitech/PSU_2016_zappy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guillobits/workspace/epitech/PSU_2016_zappy/CMakeFiles /home/guillobits/workspace/epitech/PSU_2016_zappy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guillobits/workspace/epitech/PSU_2016_zappy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PSU_2016_zappy

# Build rule for target.
PSU_2016_zappy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PSU_2016_zappy
.PHONY : PSU_2016_zappy

# fast build rule for target.
PSU_2016_zappy/fast:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/build
.PHONY : PSU_2016_zappy/fast

src/ai/src/EventHandler.o: src/ai/src/EventHandler.cpp.o

.PHONY : src/ai/src/EventHandler.o

# target to build an object file
src/ai/src/EventHandler.cpp.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/EventHandler.cpp.o
.PHONY : src/ai/src/EventHandler.cpp.o

src/ai/src/EventHandler.i: src/ai/src/EventHandler.cpp.i

.PHONY : src/ai/src/EventHandler.i

# target to preprocess a source file
src/ai/src/EventHandler.cpp.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/EventHandler.cpp.i
.PHONY : src/ai/src/EventHandler.cpp.i

src/ai/src/EventHandler.s: src/ai/src/EventHandler.cpp.s

.PHONY : src/ai/src/EventHandler.s

# target to generate assembly for a file
src/ai/src/EventHandler.cpp.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/EventHandler.cpp.s
.PHONY : src/ai/src/EventHandler.cpp.s

src/ai/src/Socket.o: src/ai/src/Socket.cpp.o

.PHONY : src/ai/src/Socket.o

# target to build an object file
src/ai/src/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/Socket.cpp.o
.PHONY : src/ai/src/Socket.cpp.o

src/ai/src/Socket.i: src/ai/src/Socket.cpp.i

.PHONY : src/ai/src/Socket.i

# target to preprocess a source file
src/ai/src/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/Socket.cpp.i
.PHONY : src/ai/src/Socket.cpp.i

src/ai/src/Socket.s: src/ai/src/Socket.cpp.s

.PHONY : src/ai/src/Socket.s

# target to generate assembly for a file
src/ai/src/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/Socket.cpp.s
.PHONY : src/ai/src/Socket.cpp.s

src/ai/src/Utils.o: src/ai/src/Utils.cpp.o

.PHONY : src/ai/src/Utils.o

# target to build an object file
src/ai/src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/Utils.cpp.o
.PHONY : src/ai/src/Utils.cpp.o

src/ai/src/Utils.i: src/ai/src/Utils.cpp.i

.PHONY : src/ai/src/Utils.i

# target to preprocess a source file
src/ai/src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/Utils.cpp.i
.PHONY : src/ai/src/Utils.cpp.i

src/ai/src/Utils.s: src/ai/src/Utils.cpp.s

.PHONY : src/ai/src/Utils.s

# target to generate assembly for a file
src/ai/src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/Utils.cpp.s
.PHONY : src/ai/src/Utils.cpp.s

src/ai/src/ZappException.o: src/ai/src/ZappException.cpp.o

.PHONY : src/ai/src/ZappException.o

# target to build an object file
src/ai/src/ZappException.cpp.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/ZappException.cpp.o
.PHONY : src/ai/src/ZappException.cpp.o

src/ai/src/ZappException.i: src/ai/src/ZappException.cpp.i

.PHONY : src/ai/src/ZappException.i

# target to preprocess a source file
src/ai/src/ZappException.cpp.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/ZappException.cpp.i
.PHONY : src/ai/src/ZappException.cpp.i

src/ai/src/ZappException.s: src/ai/src/ZappException.cpp.s

.PHONY : src/ai/src/ZappException.s

# target to generate assembly for a file
src/ai/src/ZappException.cpp.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/ZappException.cpp.s
.PHONY : src/ai/src/ZappException.cpp.s

src/ai/src/main.o: src/ai/src/main.cpp.o

.PHONY : src/ai/src/main.o

# target to build an object file
src/ai/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/main.cpp.o
.PHONY : src/ai/src/main.cpp.o

src/ai/src/main.i: src/ai/src/main.cpp.i

.PHONY : src/ai/src/main.i

# target to preprocess a source file
src/ai/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/main.cpp.i
.PHONY : src/ai/src/main.cpp.i

src/ai/src/main.s: src/ai/src/main.cpp.s

.PHONY : src/ai/src/main.s

# target to generate assembly for a file
src/ai/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/main.cpp.s
.PHONY : src/ai/src/main.cpp.s

src/ai/src/zappy.o: src/ai/src/zappy.cpp.o

.PHONY : src/ai/src/zappy.o

# target to build an object file
src/ai/src/zappy.cpp.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/zappy.cpp.o
.PHONY : src/ai/src/zappy.cpp.o

src/ai/src/zappy.i: src/ai/src/zappy.cpp.i

.PHONY : src/ai/src/zappy.i

# target to preprocess a source file
src/ai/src/zappy.cpp.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/zappy.cpp.i
.PHONY : src/ai/src/zappy.cpp.i

src/ai/src/zappy.s: src/ai/src/zappy.cpp.s

.PHONY : src/ai/src/zappy.s

# target to generate assembly for a file
src/ai/src/zappy.cpp.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/ai/src/zappy.cpp.s
.PHONY : src/ai/src/zappy.cpp.s

src/server/client.o: src/server/client.c.o

.PHONY : src/server/client.o

# target to build an object file
src/server/client.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/client.c.o
.PHONY : src/server/client.c.o

src/server/client.i: src/server/client.c.i

.PHONY : src/server/client.i

# target to preprocess a source file
src/server/client.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/client.c.i
.PHONY : src/server/client.c.i

src/server/client.s: src/server/client.c.s

.PHONY : src/server/client.s

# target to generate assembly for a file
src/server/client.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/client.c.s
.PHONY : src/server/client.c.s

src/server/command.o: src/server/command.c.o

.PHONY : src/server/command.o

# target to build an object file
src/server/command.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command.c.o
.PHONY : src/server/command.c.o

src/server/command.i: src/server/command.c.i

.PHONY : src/server/command.i

# target to preprocess a source file
src/server/command.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command.c.i
.PHONY : src/server/command.c.i

src/server/command.s: src/server/command.c.s

.PHONY : src/server/command.s

# target to generate assembly for a file
src/server/command.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command.c.s
.PHONY : src/server/command.c.s

src/server/command_b.o: src/server/command_b.c.o

.PHONY : src/server/command_b.o

# target to build an object file
src/server/command_b.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_b.c.o
.PHONY : src/server/command_b.c.o

src/server/command_b.i: src/server/command_b.c.i

.PHONY : src/server/command_b.i

# target to preprocess a source file
src/server/command_b.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_b.c.i
.PHONY : src/server/command_b.c.i

src/server/command_b.s: src/server/command_b.c.s

.PHONY : src/server/command_b.s

# target to generate assembly for a file
src/server/command_b.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_b.c.s
.PHONY : src/server/command_b.c.s

src/server/command_broadcast.o: src/server/command_broadcast.c.o

.PHONY : src/server/command_broadcast.o

# target to build an object file
src/server/command_broadcast.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_broadcast.c.o
.PHONY : src/server/command_broadcast.c.o

src/server/command_broadcast.i: src/server/command_broadcast.c.i

.PHONY : src/server/command_broadcast.i

# target to preprocess a source file
src/server/command_broadcast.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_broadcast.c.i
.PHONY : src/server/command_broadcast.c.i

src/server/command_broadcast.s: src/server/command_broadcast.c.s

.PHONY : src/server/command_broadcast.s

# target to generate assembly for a file
src/server/command_broadcast.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_broadcast.c.s
.PHONY : src/server/command_broadcast.c.s

src/server/command_connect_nbr.o: src/server/command_connect_nbr.c.o

.PHONY : src/server/command_connect_nbr.o

# target to build an object file
src/server/command_connect_nbr.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_connect_nbr.c.o
.PHONY : src/server/command_connect_nbr.c.o

src/server/command_connect_nbr.i: src/server/command_connect_nbr.c.i

.PHONY : src/server/command_connect_nbr.i

# target to preprocess a source file
src/server/command_connect_nbr.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_connect_nbr.c.i
.PHONY : src/server/command_connect_nbr.c.i

src/server/command_connect_nbr.s: src/server/command_connect_nbr.c.s

.PHONY : src/server/command_connect_nbr.s

# target to generate assembly for a file
src/server/command_connect_nbr.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_connect_nbr.c.s
.PHONY : src/server/command_connect_nbr.c.s

src/server/command_inventory.o: src/server/command_inventory.c.o

.PHONY : src/server/command_inventory.o

# target to build an object file
src/server/command_inventory.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_inventory.c.o
.PHONY : src/server/command_inventory.c.o

src/server/command_inventory.i: src/server/command_inventory.c.i

.PHONY : src/server/command_inventory.i

# target to preprocess a source file
src/server/command_inventory.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_inventory.c.i
.PHONY : src/server/command_inventory.c.i

src/server/command_inventory.s: src/server/command_inventory.c.s

.PHONY : src/server/command_inventory.s

# target to generate assembly for a file
src/server/command_inventory.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_inventory.c.s
.PHONY : src/server/command_inventory.c.s

src/server/command_look.o: src/server/command_look.c.o

.PHONY : src/server/command_look.o

# target to build an object file
src/server/command_look.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_look.c.o
.PHONY : src/server/command_look.c.o

src/server/command_look.i: src/server/command_look.c.i

.PHONY : src/server/command_look.i

# target to preprocess a source file
src/server/command_look.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_look.c.i
.PHONY : src/server/command_look.c.i

src/server/command_look.s: src/server/command_look.c.s

.PHONY : src/server/command_look.s

# target to generate assembly for a file
src/server/command_look.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_look.c.s
.PHONY : src/server/command_look.c.s

src/server/command_map.o: src/server/command_map.c.o

.PHONY : src/server/command_map.o

# target to build an object file
src/server/command_map.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_map.c.o
.PHONY : src/server/command_map.c.o

src/server/command_map.i: src/server/command_map.c.i

.PHONY : src/server/command_map.i

# target to preprocess a source file
src/server/command_map.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_map.c.i
.PHONY : src/server/command_map.c.i

src/server/command_map.s: src/server/command_map.c.s

.PHONY : src/server/command_map.s

# target to generate assembly for a file
src/server/command_map.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_map.c.s
.PHONY : src/server/command_map.c.s

src/server/command_move_player.o: src/server/command_move_player.c.o

.PHONY : src/server/command_move_player.o

# target to build an object file
src/server/command_move_player.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_move_player.c.o
.PHONY : src/server/command_move_player.c.o

src/server/command_move_player.i: src/server/command_move_player.c.i

.PHONY : src/server/command_move_player.i

# target to preprocess a source file
src/server/command_move_player.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_move_player.c.i
.PHONY : src/server/command_move_player.c.i

src/server/command_move_player.s: src/server/command_move_player.c.s

.PHONY : src/server/command_move_player.s

# target to generate assembly for a file
src/server/command_move_player.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_move_player.c.s
.PHONY : src/server/command_move_player.c.s

src/server/command_pin.o: src/server/command_pin.c.o

.PHONY : src/server/command_pin.o

# target to build an object file
src/server/command_pin.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_pin.c.o
.PHONY : src/server/command_pin.c.o

src/server/command_pin.i: src/server/command_pin.c.i

.PHONY : src/server/command_pin.i

# target to preprocess a source file
src/server/command_pin.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_pin.c.i
.PHONY : src/server/command_pin.c.i

src/server/command_pin.s: src/server/command_pin.c.s

.PHONY : src/server/command_pin.s

# target to generate assembly for a file
src/server/command_pin.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_pin.c.s
.PHONY : src/server/command_pin.c.s

src/server/command_player.o: src/server/command_player.c.o

.PHONY : src/server/command_player.o

# target to build an object file
src/server/command_player.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_player.c.o
.PHONY : src/server/command_player.c.o

src/server/command_player.i: src/server/command_player.c.i

.PHONY : src/server/command_player.i

# target to preprocess a source file
src/server/command_player.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_player.c.i
.PHONY : src/server/command_player.c.i

src/server/command_player.s: src/server/command_player.c.s

.PHONY : src/server/command_player.s

# target to generate assembly for a file
src/server/command_player.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_player.c.s
.PHONY : src/server/command_player.c.s

src/server/command_put_object.o: src/server/command_put_object.c.o

.PHONY : src/server/command_put_object.o

# target to build an object file
src/server/command_put_object.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_put_object.c.o
.PHONY : src/server/command_put_object.c.o

src/server/command_put_object.i: src/server/command_put_object.c.i

.PHONY : src/server/command_put_object.i

# target to preprocess a source file
src/server/command_put_object.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_put_object.c.i
.PHONY : src/server/command_put_object.c.i

src/server/command_put_object.s: src/server/command_put_object.c.s

.PHONY : src/server/command_put_object.s

# target to generate assembly for a file
src/server/command_put_object.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_put_object.c.s
.PHONY : src/server/command_put_object.c.s

src/server/command_sgt.o: src/server/command_sgt.c.o

.PHONY : src/server/command_sgt.o

# target to build an object file
src/server/command_sgt.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_sgt.c.o
.PHONY : src/server/command_sgt.c.o

src/server/command_sgt.i: src/server/command_sgt.c.i

.PHONY : src/server/command_sgt.i

# target to preprocess a source file
src/server/command_sgt.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_sgt.c.i
.PHONY : src/server/command_sgt.c.i

src/server/command_sgt.s: src/server/command_sgt.c.s

.PHONY : src/server/command_sgt.s

# target to generate assembly for a file
src/server/command_sgt.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_sgt.c.s
.PHONY : src/server/command_sgt.c.s

src/server/command_take_object.o: src/server/command_take_object.c.o

.PHONY : src/server/command_take_object.o

# target to build an object file
src/server/command_take_object.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_take_object.c.o
.PHONY : src/server/command_take_object.c.o

src/server/command_take_object.i: src/server/command_take_object.c.i

.PHONY : src/server/command_take_object.i

# target to preprocess a source file
src/server/command_take_object.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_take_object.c.i
.PHONY : src/server/command_take_object.c.i

src/server/command_take_object.s: src/server/command_take_object.c.s

.PHONY : src/server/command_take_object.s

# target to generate assembly for a file
src/server/command_take_object.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_take_object.c.s
.PHONY : src/server/command_take_object.c.s

src/server/command_team.o: src/server/command_team.c.o

.PHONY : src/server/command_team.o

# target to build an object file
src/server/command_team.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_team.c.o
.PHONY : src/server/command_team.c.o

src/server/command_team.i: src/server/command_team.c.i

.PHONY : src/server/command_team.i

# target to preprocess a source file
src/server/command_team.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_team.c.i
.PHONY : src/server/command_team.c.i

src/server/command_team.s: src/server/command_team.c.s

.PHONY : src/server/command_team.s

# target to generate assembly for a file
src/server/command_team.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/command_team.c.s
.PHONY : src/server/command_team.c.s

src/server/communication.o: src/server/communication.c.o

.PHONY : src/server/communication.o

# target to build an object file
src/server/communication.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/communication.c.o
.PHONY : src/server/communication.c.o

src/server/communication.i: src/server/communication.c.i

.PHONY : src/server/communication.i

# target to preprocess a source file
src/server/communication.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/communication.c.i
.PHONY : src/server/communication.c.i

src/server/communication.s: src/server/communication.c.s

.PHONY : src/server/communication.s

# target to generate assembly for a file
src/server/communication.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/communication.c.s
.PHONY : src/server/communication.c.s

src/server/connection_client.o: src/server/connection_client.c.o

.PHONY : src/server/connection_client.o

# target to build an object file
src/server/connection_client.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/connection_client.c.o
.PHONY : src/server/connection_client.c.o

src/server/connection_client.i: src/server/connection_client.c.i

.PHONY : src/server/connection_client.i

# target to preprocess a source file
src/server/connection_client.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/connection_client.c.i
.PHONY : src/server/connection_client.c.i

src/server/connection_client.s: src/server/connection_client.c.s

.PHONY : src/server/connection_client.s

# target to generate assembly for a file
src/server/connection_client.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/connection_client.c.s
.PHONY : src/server/connection_client.c.s

src/server/execute_command.o: src/server/execute_command.c.o

.PHONY : src/server/execute_command.o

# target to build an object file
src/server/execute_command.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/execute_command.c.o
.PHONY : src/server/execute_command.c.o

src/server/execute_command.i: src/server/execute_command.c.i

.PHONY : src/server/execute_command.i

# target to preprocess a source file
src/server/execute_command.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/execute_command.c.i
.PHONY : src/server/execute_command.c.i

src/server/execute_command.s: src/server/execute_command.c.s

.PHONY : src/server/execute_command.s

# target to generate assembly for a file
src/server/execute_command.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/execute_command.c.s
.PHONY : src/server/execute_command.c.s

src/server/handle_io.o: src/server/handle_io.c.o

.PHONY : src/server/handle_io.o

# target to build an object file
src/server/handle_io.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/handle_io.c.o
.PHONY : src/server/handle_io.c.o

src/server/handle_io.i: src/server/handle_io.c.i

.PHONY : src/server/handle_io.i

# target to preprocess a source file
src/server/handle_io.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/handle_io.c.i
.PHONY : src/server/handle_io.c.i

src/server/handle_io.s: src/server/handle_io.c.s

.PHONY : src/server/handle_io.s

# target to generate assembly for a file
src/server/handle_io.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/handle_io.c.s
.PHONY : src/server/handle_io.c.s

src/server/handle_parsing.o: src/server/handle_parsing.c.o

.PHONY : src/server/handle_parsing.o

# target to build an object file
src/server/handle_parsing.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/handle_parsing.c.o
.PHONY : src/server/handle_parsing.c.o

src/server/handle_parsing.i: src/server/handle_parsing.c.i

.PHONY : src/server/handle_parsing.i

# target to preprocess a source file
src/server/handle_parsing.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/handle_parsing.c.i
.PHONY : src/server/handle_parsing.c.i

src/server/handle_parsing.s: src/server/handle_parsing.c.s

.PHONY : src/server/handle_parsing.s

# target to generate assembly for a file
src/server/handle_parsing.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/handle_parsing.c.s
.PHONY : src/server/handle_parsing.c.s

src/server/lib/list.o: src/server/lib/list.c.o

.PHONY : src/server/lib/list.o

# target to build an object file
src/server/lib/list.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/list.c.o
.PHONY : src/server/lib/list.c.o

src/server/lib/list.i: src/server/lib/list.c.i

.PHONY : src/server/lib/list.i

# target to preprocess a source file
src/server/lib/list.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/list.c.i
.PHONY : src/server/lib/list.c.i

src/server/lib/list.s: src/server/lib/list.c.s

.PHONY : src/server/lib/list.s

# target to generate assembly for a file
src/server/lib/list.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/list.c.s
.PHONY : src/server/lib/list.c.s

src/server/lib/send.o: src/server/lib/send.c.o

.PHONY : src/server/lib/send.o

# target to build an object file
src/server/lib/send.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/send.c.o
.PHONY : src/server/lib/send.c.o

src/server/lib/send.i: src/server/lib/send.c.i

.PHONY : src/server/lib/send.i

# target to preprocess a source file
src/server/lib/send.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/send.c.i
.PHONY : src/server/lib/send.c.i

src/server/lib/send.s: src/server/lib/send.c.s

.PHONY : src/server/lib/send.s

# target to generate assembly for a file
src/server/lib/send.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/send.c.s
.PHONY : src/server/lib/send.c.s

src/server/lib/string.o: src/server/lib/string.c.o

.PHONY : src/server/lib/string.o

# target to build an object file
src/server/lib/string.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/string.c.o
.PHONY : src/server/lib/string.c.o

src/server/lib/string.i: src/server/lib/string.c.i

.PHONY : src/server/lib/string.i

# target to preprocess a source file
src/server/lib/string.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/string.c.i
.PHONY : src/server/lib/string.c.i

src/server/lib/string.s: src/server/lib/string.c.s

.PHONY : src/server/lib/string.s

# target to generate assembly for a file
src/server/lib/string.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/lib/string.c.s
.PHONY : src/server/lib/string.c.s

src/server/look_utils.o: src/server/look_utils.c.o

.PHONY : src/server/look_utils.o

# target to build an object file
src/server/look_utils.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/look_utils.c.o
.PHONY : src/server/look_utils.c.o

src/server/look_utils.i: src/server/look_utils.c.i

.PHONY : src/server/look_utils.i

# target to preprocess a source file
src/server/look_utils.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/look_utils.c.i
.PHONY : src/server/look_utils.c.i

src/server/look_utils.s: src/server/look_utils.c.s

.PHONY : src/server/look_utils.s

# target to generate assembly for a file
src/server/look_utils.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/look_utils.c.s
.PHONY : src/server/look_utils.c.s

src/server/main.o: src/server/main.c.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/main.c.o
.PHONY : src/server/main.c.o

src/server/main.i: src/server/main.c.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/main.c.i
.PHONY : src/server/main.c.i

src/server/main.s: src/server/main.c.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/main.c.s
.PHONY : src/server/main.c.s

src/server/map.o: src/server/map.c.o

.PHONY : src/server/map.o

# target to build an object file
src/server/map.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/map.c.o
.PHONY : src/server/map.c.o

src/server/map.i: src/server/map.c.i

.PHONY : src/server/map.i

# target to preprocess a source file
src/server/map.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/map.c.i
.PHONY : src/server/map.c.i

src/server/map.s: src/server/map.c.s

.PHONY : src/server/map.s

# target to generate assembly for a file
src/server/map.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/map.c.s
.PHONY : src/server/map.c.s

src/server/player.o: src/server/player.c.o

.PHONY : src/server/player.o

# target to build an object file
src/server/player.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/player.c.o
.PHONY : src/server/player.c.o

src/server/player.i: src/server/player.c.i

.PHONY : src/server/player.i

# target to preprocess a source file
src/server/player.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/player.c.i
.PHONY : src/server/player.c.i

src/server/player.s: src/server/player.c.s

.PHONY : src/server/player.s

# target to generate assembly for a file
src/server/player.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/player.c.s
.PHONY : src/server/player.c.s

src/server/player_b.o: src/server/player_b.c.o

.PHONY : src/server/player_b.o

# target to build an object file
src/server/player_b.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/player_b.c.o
.PHONY : src/server/player_b.c.o

src/server/player_b.i: src/server/player_b.c.i

.PHONY : src/server/player_b.i

# target to preprocess a source file
src/server/player_b.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/player_b.c.i
.PHONY : src/server/player_b.c.i

src/server/player_b.s: src/server/player_b.c.s

.PHONY : src/server/player_b.s

# target to generate assembly for a file
src/server/player_b.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/player_b.c.s
.PHONY : src/server/player_b.c.s

src/server/print_vision_a.o: src/server/print_vision_a.c.o

.PHONY : src/server/print_vision_a.o

# target to build an object file
src/server/print_vision_a.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/print_vision_a.c.o
.PHONY : src/server/print_vision_a.c.o

src/server/print_vision_a.i: src/server/print_vision_a.c.i

.PHONY : src/server/print_vision_a.i

# target to preprocess a source file
src/server/print_vision_a.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/print_vision_a.c.i
.PHONY : src/server/print_vision_a.c.i

src/server/print_vision_a.s: src/server/print_vision_a.c.s

.PHONY : src/server/print_vision_a.s

# target to generate assembly for a file
src/server/print_vision_a.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/print_vision_a.c.s
.PHONY : src/server/print_vision_a.c.s

src/server/print_vision_b.o: src/server/print_vision_b.c.o

.PHONY : src/server/print_vision_b.o

# target to build an object file
src/server/print_vision_b.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/print_vision_b.c.o
.PHONY : src/server/print_vision_b.c.o

src/server/print_vision_b.i: src/server/print_vision_b.c.i

.PHONY : src/server/print_vision_b.i

# target to preprocess a source file
src/server/print_vision_b.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/print_vision_b.c.i
.PHONY : src/server/print_vision_b.c.i

src/server/print_vision_b.s: src/server/print_vision_b.c.s

.PHONY : src/server/print_vision_b.s

# target to generate assembly for a file
src/server/print_vision_b.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/print_vision_b.c.s
.PHONY : src/server/print_vision_b.c.s

src/server/server.o: src/server/server.c.o

.PHONY : src/server/server.o

# target to build an object file
src/server/server.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/server.c.o
.PHONY : src/server/server.c.o

src/server/server.i: src/server/server.c.i

.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/server.c.i
.PHONY : src/server/server.c.i

src/server/server.s: src/server/server.c.s

.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/server.c.s
.PHONY : src/server/server.c.s

src/server/socket.o: src/server/socket.c.o

.PHONY : src/server/socket.o

# target to build an object file
src/server/socket.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/socket.c.o
.PHONY : src/server/socket.c.o

src/server/socket.i: src/server/socket.c.i

.PHONY : src/server/socket.i

# target to preprocess a source file
src/server/socket.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/socket.c.i
.PHONY : src/server/socket.c.i

src/server/socket.s: src/server/socket.c.s

.PHONY : src/server/socket.s

# target to generate assembly for a file
src/server/socket.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/socket.c.s
.PHONY : src/server/socket.c.s

src/server/team.o: src/server/team.c.o

.PHONY : src/server/team.o

# target to build an object file
src/server/team.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/team.c.o
.PHONY : src/server/team.c.o

src/server/team.i: src/server/team.c.i

.PHONY : src/server/team.i

# target to preprocess a source file
src/server/team.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/team.c.i
.PHONY : src/server/team.c.i

src/server/team.s: src/server/team.c.s

.PHONY : src/server/team.s

# target to generate assembly for a file
src/server/team.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/team.c.s
.PHONY : src/server/team.c.s

src/server/utils_object_commands.o: src/server/utils_object_commands.c.o

.PHONY : src/server/utils_object_commands.o

# target to build an object file
src/server/utils_object_commands.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/utils_object_commands.c.o
.PHONY : src/server/utils_object_commands.c.o

src/server/utils_object_commands.i: src/server/utils_object_commands.c.i

.PHONY : src/server/utils_object_commands.i

# target to preprocess a source file
src/server/utils_object_commands.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/utils_object_commands.c.i
.PHONY : src/server/utils_object_commands.c.i

src/server/utils_object_commands.s: src/server/utils_object_commands.c.s

.PHONY : src/server/utils_object_commands.s

# target to generate assembly for a file
src/server/utils_object_commands.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/utils_object_commands.c.s
.PHONY : src/server/utils_object_commands.c.s

src/server/utils_parsing.o: src/server/utils_parsing.c.o

.PHONY : src/server/utils_parsing.o

# target to build an object file
src/server/utils_parsing.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/utils_parsing.c.o
.PHONY : src/server/utils_parsing.c.o

src/server/utils_parsing.i: src/server/utils_parsing.c.i

.PHONY : src/server/utils_parsing.i

# target to preprocess a source file
src/server/utils_parsing.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/utils_parsing.c.i
.PHONY : src/server/utils_parsing.c.i

src/server/utils_parsing.s: src/server/utils_parsing.c.s

.PHONY : src/server/utils_parsing.s

# target to generate assembly for a file
src/server/utils_parsing.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/utils_parsing.c.s
.PHONY : src/server/utils_parsing.c.s

src/server/waiting_cmds.o: src/server/waiting_cmds.c.o

.PHONY : src/server/waiting_cmds.o

# target to build an object file
src/server/waiting_cmds.c.o:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/waiting_cmds.c.o
.PHONY : src/server/waiting_cmds.c.o

src/server/waiting_cmds.i: src/server/waiting_cmds.c.i

.PHONY : src/server/waiting_cmds.i

# target to preprocess a source file
src/server/waiting_cmds.c.i:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/waiting_cmds.c.i
.PHONY : src/server/waiting_cmds.c.i

src/server/waiting_cmds.s: src/server/waiting_cmds.c.s

.PHONY : src/server/waiting_cmds.s

# target to generate assembly for a file
src/server/waiting_cmds.c.s:
	$(MAKE) -f CMakeFiles/PSU_2016_zappy.dir/build.make CMakeFiles/PSU_2016_zappy.dir/src/server/waiting_cmds.c.s
.PHONY : src/server/waiting_cmds.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PSU_2016_zappy"
	@echo "... src/ai/src/EventHandler.o"
	@echo "... src/ai/src/EventHandler.i"
	@echo "... src/ai/src/EventHandler.s"
	@echo "... src/ai/src/Socket.o"
	@echo "... src/ai/src/Socket.i"
	@echo "... src/ai/src/Socket.s"
	@echo "... src/ai/src/Utils.o"
	@echo "... src/ai/src/Utils.i"
	@echo "... src/ai/src/Utils.s"
	@echo "... src/ai/src/ZappException.o"
	@echo "... src/ai/src/ZappException.i"
	@echo "... src/ai/src/ZappException.s"
	@echo "... src/ai/src/main.o"
	@echo "... src/ai/src/main.i"
	@echo "... src/ai/src/main.s"
	@echo "... src/ai/src/zappy.o"
	@echo "... src/ai/src/zappy.i"
	@echo "... src/ai/src/zappy.s"
	@echo "... src/server/client.o"
	@echo "... src/server/client.i"
	@echo "... src/server/client.s"
	@echo "... src/server/command.o"
	@echo "... src/server/command.i"
	@echo "... src/server/command.s"
	@echo "... src/server/command_b.o"
	@echo "... src/server/command_b.i"
	@echo "... src/server/command_b.s"
	@echo "... src/server/command_broadcast.o"
	@echo "... src/server/command_broadcast.i"
	@echo "... src/server/command_broadcast.s"
	@echo "... src/server/command_connect_nbr.o"
	@echo "... src/server/command_connect_nbr.i"
	@echo "... src/server/command_connect_nbr.s"
	@echo "... src/server/command_inventory.o"
	@echo "... src/server/command_inventory.i"
	@echo "... src/server/command_inventory.s"
	@echo "... src/server/command_look.o"
	@echo "... src/server/command_look.i"
	@echo "... src/server/command_look.s"
	@echo "... src/server/command_map.o"
	@echo "... src/server/command_map.i"
	@echo "... src/server/command_map.s"
	@echo "... src/server/command_move_player.o"
	@echo "... src/server/command_move_player.i"
	@echo "... src/server/command_move_player.s"
	@echo "... src/server/command_pin.o"
	@echo "... src/server/command_pin.i"
	@echo "... src/server/command_pin.s"
	@echo "... src/server/command_player.o"
	@echo "... src/server/command_player.i"
	@echo "... src/server/command_player.s"
	@echo "... src/server/command_put_object.o"
	@echo "... src/server/command_put_object.i"
	@echo "... src/server/command_put_object.s"
	@echo "... src/server/command_sgt.o"
	@echo "... src/server/command_sgt.i"
	@echo "... src/server/command_sgt.s"
	@echo "... src/server/command_take_object.o"
	@echo "... src/server/command_take_object.i"
	@echo "... src/server/command_take_object.s"
	@echo "... src/server/command_team.o"
	@echo "... src/server/command_team.i"
	@echo "... src/server/command_team.s"
	@echo "... src/server/communication.o"
	@echo "... src/server/communication.i"
	@echo "... src/server/communication.s"
	@echo "... src/server/connection_client.o"
	@echo "... src/server/connection_client.i"
	@echo "... src/server/connection_client.s"
	@echo "... src/server/execute_command.o"
	@echo "... src/server/execute_command.i"
	@echo "... src/server/execute_command.s"
	@echo "... src/server/handle_io.o"
	@echo "... src/server/handle_io.i"
	@echo "... src/server/handle_io.s"
	@echo "... src/server/handle_parsing.o"
	@echo "... src/server/handle_parsing.i"
	@echo "... src/server/handle_parsing.s"
	@echo "... src/server/lib/list.o"
	@echo "... src/server/lib/list.i"
	@echo "... src/server/lib/list.s"
	@echo "... src/server/lib/send.o"
	@echo "... src/server/lib/send.i"
	@echo "... src/server/lib/send.s"
	@echo "... src/server/lib/string.o"
	@echo "... src/server/lib/string.i"
	@echo "... src/server/lib/string.s"
	@echo "... src/server/look_utils.o"
	@echo "... src/server/look_utils.i"
	@echo "... src/server/look_utils.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/map.o"
	@echo "... src/server/map.i"
	@echo "... src/server/map.s"
	@echo "... src/server/player.o"
	@echo "... src/server/player.i"
	@echo "... src/server/player.s"
	@echo "... src/server/player_b.o"
	@echo "... src/server/player_b.i"
	@echo "... src/server/player_b.s"
	@echo "... src/server/print_vision_a.o"
	@echo "... src/server/print_vision_a.i"
	@echo "... src/server/print_vision_a.s"
	@echo "... src/server/print_vision_b.o"
	@echo "... src/server/print_vision_b.i"
	@echo "... src/server/print_vision_b.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
	@echo "... src/server/socket.o"
	@echo "... src/server/socket.i"
	@echo "... src/server/socket.s"
	@echo "... src/server/team.o"
	@echo "... src/server/team.i"
	@echo "... src/server/team.s"
	@echo "... src/server/utils_object_commands.o"
	@echo "... src/server/utils_object_commands.i"
	@echo "... src/server/utils_object_commands.s"
	@echo "... src/server/utils_parsing.o"
	@echo "... src/server/utils_parsing.i"
	@echo "... src/server/utils_parsing.s"
	@echo "... src/server/waiting_cmds.o"
	@echo "... src/server/waiting_cmds.i"
	@echo "... src/server/waiting_cmds.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

